# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_blogger_post_list:
    pattern: /
    defaults: { _controller: sylius_blogger.controller.frontend.post:listAction }

sylius_blogger_post_show:
    pattern: /{slug}
    defaults: { _controller: sylius_blogger.controller.frontend.post:showAction }
